# Generated by Django 5.2.1 on 2025-05-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('tech_Tack', models.TextField()),
                ('programmer', models.CharField()),
                ('image', models.IntegerField(default='kk.jpg')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
