# Generated by Django 5.2.1 on 2025-05-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectformat',
            name='image',
            field=models.ImageField(default='kk.jpg', upload_to=''),
        ),
    ]
