# Generated by Django 5.2.1 on 2025-06-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_projectformat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectformat',
            name='projectlink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
